openapi: "3.0.1"
info:
  title: Job Service
paths:
  "/jobs":
    post:
      responses:
        # default:
        #   description: Successful operation
        "201":
          description: Successful operation
          # responseTemplates :
          #   "application/json" : "#set ($root=$input.path('$')) { \"stage\": \"$root.name\", \"user-id\": \"$root.key\" }"
      x-amazon-apigateway-integration:
        integrationSubtype: SQS-SendMessage
        credentials: !GetAtt HttpApiRole.Arn
        requestParameters:
          MessageBody: $request.body
          QueueUrl: !Ref InputQueue
        responses:
          default:
            statusCode: "201"
            responseTemplates :
              "application/json" : '{"message": "This is response message"}'
              # "application/json" : "#set ($root=$input.path('$')) { \"stage\": \"$root.name\", \"user-id\": \"$root.key\" }"
        payloadFormatVersion: "1.0"
        type: aws_proxy
        connectionType: INTERNET