openapi: "3.0.1"
info:
  title: Using SQS to buffer Create Job requests
paths:
  "/jobs":
    post:
      responses:
        default:
          description: Successful operation
      x-amazon-apigateway-integration:
        integrationSubtype: SQS-SendMessage
        credentials: !GetAtt HttpApiRole.Arn
        requestParameters:
          MessageBody: $request.body
          QueueUrl: !Ref InputQueue
        responses:
          "200":
            statusCode: 201
            responseTemplates :
              "application/json" : "#set ($root=$input.path('$')) { \"stage\": \"$root.name\", \"user-id\": \"$root.key\" }",
              "application/xml" : "#set ($root=$input.path('$')) <stage>$root.name</stage> "
        payloadFormatVersion: "1.0"
        type: aws_proxy
        connectionType: INTERNET