service: job-pattern-one

licenseKey: ${ssm:/aws/reference/secretsmanager/serverless-framework-access-key}

configValidationMode: error

provider:
  architecture: arm64
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  environment:
    EVENT_BUS_NAME: ${self:custom.eventBusName}
    TABLE_NAME: ${self:custom.tableName}
  logRetentionInDays: 7
  name: aws
  runtime: nodejs18.x
  stage: dev
  tags:
    lumigo:auto-trace: 'true'

custom:
  eventBusName: ${self:service}
  prune:
    automatic: true
    number: 1
  tableName: ${self:service}

functions:
  createJob:
    handler: jobs/handlers/createJob.default
    events:
    - httpApi:
        method: POST
        path: /jobs
    iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: !GetAtt JobsTable.Arn

  getJob:
    handler: jobs/handlers/getJob.default
    events:
    - httpApi:
        method: GET
        path: /jobs/{jobId}
    iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:GetItem
      Resource: !GetAtt JobsTable.Arn

  ## Events  
  onDbStreamEvent:
    handler: jobs/handlers/onDbStreamEvent.default
    events:
    - stream:
        type: dynamodb
        arn: !GetAtt JobsTable.StreamArn
        batchSize: 10
    iamRoleStatements:
    - Effect: Allow
      Action: events:PutEvents
      Resource: !GetAtt JobsEventBus.Arn

  onJobCreated:
    handler: jobs/handlers/onJobCreated.default
    environment:
      TRANSLATE_STATE_MACHINE_ARN: !Ref TranslateStateMachine
    events:
    - eventBridge:
        eventBus: !GetAtt JobsEventBus.Name
        pattern:
          source:
          - job
          detail-type:
          - create
    iamRoleStatements:
    - Effect: Allow
      Action: states:StartExecution
      Resource: !Ref TranslateStateMachine

  ## Step Function Lambdas
  setJobStatusStarted:
    handler: jobs/handlers/setJobStatusStarted.default
    environment:
      LUMIGO_STEP_FUNCTION: 'TRUE'
    iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:UpdateItem
      Resource: !GetAtt JobsTable.Arn

  translatePhrase:
    handler: jobs/handlers/translatePhrase.default
    environment:
      LUMIGO_STEP_FUNCTION: 'TRUE'

  setJobStatusComplete:
    handler: jobs/handlers/setJobStatusComplete.default
    environment:
      LUMIGO_STEP_FUNCTION: 'TRUE'
    iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:UpdateItem
      Resource: !GetAtt JobsTable.Arn
      
  setJobStatusFailed:
    handler: jobs/handlers/setJobStatusFailed.default
    environment:
      LUMIGO_STEP_FUNCTION: 'TRUE'
    iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:UpdateItem
      Resource: !GetAtt JobsTable.Arn

stepFunctions:
  validate: true
  stateMachines:
    translateStateMachine:
      name: TranslateStateMachine
      type: EXPRESS
      loggingConfig:
        level: ALL
        includeExecutionData: false
        destinations: 
        - !GetAtt TranslateStateMachineLogGroup.Arn
      definition:
        StartAt: Set Job Status Started
        States:
          Set Job Status Started:
            Type: Task
            Resource: !GetAtt setJobStatusStarted.Arn
            Retry:
            - ErrorEquals: [States.ALL]
              IntervalSeconds: 2
              MaxAttempts: 3
              BackoffRate: 2
            Catch:
            - ErrorEquals: [States.ALL]
              ResultPath: $.error
              Next: Set Job Status Failed
            Next: Translate Phrase
          Translate Phrase:
            Type: Task
            Resource: !GetAtt translatePhrase.Arn
            Retry:
            - ErrorEquals: [States.ALL]
              IntervalSeconds: 2
              MaxAttempts: 3
              BackoffRate: 2
            Catch:
            - ErrorEquals: [States.ALL]
              ResultPath: $.error
              Next: Set Job Status Failed
            Next: Set Job Status Completed
          Set Job Status Completed:
            Type: Task
            Resource: !GetAtt setJobStatusComplete.Arn
            Retry:
            - ErrorEquals: [States.ALL]
              IntervalSeconds: 2
              MaxAttempts: 3
              BackoffRate: 2
            Catch:
            - ErrorEquals: [States.ALL]
              ResultPath: $.error
              Next: Set Job Status Failed
            End: true
          Set Job Status Failed:
            Type: Task
            Resource: !GetAtt setJobStatusFailed.Arn
            Next: Fail
          Fail:
            Type: Fail

resources:
  Resources:
    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        ContributorInsightsSpecification:
          Enabled: true
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: True
    JobsEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.eventBusName}
    TranslateStateMachineLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Join ['/', [stepfunctions, TranslateStateMachine]]

build:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - '@aws-sdk/*'

package:
  individually: true

plugins:
- serverless-iam-roles-per-function
- serverless-deployment-bucket
- serverless-step-functions