service: job-pattern-one

frameworkVersion: ^3

configValidationMode: error

provider:
  architecture: arm64
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  logRetentionInDays: 7
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  tags:
    lumigo:auto-trace: 'true'

functions:
  createJob:
    handler: jobs/handlers/saveJob.default
    events:
    - httpApi:
        method: POST
        path: /jobs
    iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:PutItem
      Resource: !GetAtt JobsTable.Arn


custom:
  esbuild:
    minify: true
  prune:
    automatic: true
    number: 1
  tableName: jobs-${sls:stage}

resources:
  Resources:
    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
        ContributorInsightsSpecification:
          Enabled: true
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

plugins:
- serverless-esbuild
- serverless-iam-roles-per-function
- serverless-deployment-bucket
- serverless-prune-plugin